# Generated by Django 4.2.15 on 2024-09-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
